apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/eladbe96/private-repo-ArgoCD.git
  password: #TOKEN
  username: ArgoCD