apiVersion: v1
kind: Secret
metadata:
  name: private-repo-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:eladbe96/private-repo-ArgoCD.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
     b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
     NhAAAAAwEAAQAAAYEAt+knCS9hdeU8GQyIvaoGrkMbpW7cjNA4Fw2e38AqH6qBxLVjDl8c
     1NG4ehAjeEUmpTZ+HQye+tvvqYESqszE4Rt19IOGYGo1a6STC3fUbiZL1hCQ5SLSOwWqHI
     VFG+fejp27xxAItJ8RqQtiZbIcwhqTR9fSLBVXFaskjPbyIVy+EWwPP2uaGc74ixGlgNB2
     LaHTQP4Y2/YPKUJo/VM1c11o20TmoOWgdxk6fhm4CiHW7djR1roCuQ0el95ARE5mYQaOsB
     k67s4at5+HQIqZT6yOqYQDc96CCGzB7ajVQmTcWKbM9SRXAN1C5A/VEyQadK4FvZ0oRj+p
     KNF3wqN80o3Bnt+c1w3y+NArbTGfYa1Rr8MTuZYXH6mBktFs+bsHpYncHUe/0SJVVaKM8y
     UflvtRHwDuM6uYwN+fqRIJ6vltvjbbp4RW3y2iNoSJIgV/haAVrZY/aLHSUTu+DRuYDOeY
     6Mw7eVKrFeZCmHvQHbEJB44BEmq7txUL/osiUWANAAAFiIJ/Oi+CfzovAAAAB3NzaC1yc2
     EAAAGBALfpJwkvYXXlPBkMiL2qBq5DG6Vu3IzQOBcNnt/AKh+qgcS1Yw5fHNTRuHoQI3hF
     JqU2fh0Mnvrb76mBEqrMxOEbdfSDhmBqNWukkwt31G4mS9YQkOUi0jsFqhyFRRvn3o6du8
     cQCLSfEakLYmWyHMIak0fX0iwVVxWrJIz28iFcvhFsDz9rmhnO+IsRpYDQdi2h00D+GNv2
     DylCaP1TNXNdaNtE5qDloHcZOn4ZuAoh1u3Y0da6ArkNHpfeQEROZmEGjrAZOu7OGrefh0
     CKmU+sjqmEA3Pegghswe2o1UJk3FimzPUkVwDdQuQP1RMkGnSuBb2dKEY/qSjRd8KjfNKN
     wZ7fnNcN8vjQK20xn2GtUa/DE7mWFx+pgZLRbPm7B6WJ3B1Hv9EiVVWijPMlH5b7UR8A7j
     OrmMDfn6kSCer5bb4226eEVt8tojaEiSIFf4WgFa2WP2ix0lE7vg0bmAznmOjMO3lSqxXm
     Qph70B2xCQeOARJqu7cVC/6LIlFgDQAAAAMBAAEAAAGAKw77hLsDJoc1OugkW8OjLMmpf2
     IlYRKfD0axG9HyCtfw6g1N09+Q8ILpniqJI2+NTMElZce+sR0tT5JYvISU09+KDmV84LX9
     K+asRtMXeXKd7tCSHBO7BPaejW7mb1IqWVm0zTaD00Yq7FkuAIFjGk7+jKOLIacdbIVVWW
     u35PfByHJ0X3Th74j1yBmpli84fBaXT3AugdFqW06hJi6FJS2Jj0zicmlQ2JGfkEaVQEoL
     +EP7XTrPyGO59fSjN1rjV3IA/8CBbE5tu67wcTWpxeRuI/5zY05phq5anTw25HG9Pi4ky/
     YCBNpBiIL/qcTXqNRzBxvRrtt0j1Fgvh+8JWUUcGHwTdLPYBdFkXoZruHNPlBFeGx0RlW8
     t7i/70vfaq6m5WyDLbhAFUS/1Oo92+Lm6pRxl1PzhO6jqSlY8A6xMajNL2dAM6LGCuk7Co
     yHZhmESKHD5z7vRqnzUk+XZta4DSVgFvuq2KmJwpSom8IQgfHLwnoerpNaQ3OFzhpBAAAA
     wQCupM3W3OwDcrb6ggOEtfUQsWMF8t6PjvnEPPqzAm72Op2vBdT6qnVjY6jIzLabrZ/pvv
     4arxcEgBzqJJ1Vfxu6RRoleL6QVqK17c1uWQ+TKIUS+KFGw5jSJkZqvShH157Y0uLY1T47
     POAUw1DYysXX7hqummkplAIKcvcWtPlbWYuhn1WzwYZJSXsivPrljGYHa9112Qp930O6KO
     DuupjxXL/UjH593ntVCBhY+b1nVtrCz28bghM1YVUcDoMtB/wAAADBAO02kKAPU+Ki9HwT
     sD3WxS5Dwpvx7WiKe68TS1008f/EdocgPfVCdW180lhctHUW2QYhCZrSi6PXx0WTzBYLer
     2hC/2WBrPUIwO6CNdKJvY7ht9cH8vheFndWOS6T621OCa87aUjUlVS+qPQ/wiSt1mvF7LP
     RqsH7iXu51KO0Dm/YybiTeq3MeXApe9t4ZektnsY4IiSOqBaeeOWJ6QGXG/pBTYgJwBWBD
     BfO5PrubLpFKygvgHyHNTfsDQinFjYgwAAAMEAxnnlNR5wCxpuZ+oi0gRDQPBWdO9kw310
     Pspb8YGzMv/vkDN9Nmz+OXp+YXJj8P8VbL89WDMbhZ+d52m3KT++ueBEFl6p5T4hU72ule
     jix+H5QrIrCoDjVLZ8RrEDiTkV2/8XPmzkoyCKyTqlPwZ7W3Mmx0yuAs67AfHpU1vzD91k
     AwJanTpU1721Txvk3/DnKXp86riH+BOzGJq+P2QWIjsxIX9HhRH6HHHl+z8EQgcECby3YY
     Y3KfuND9nSBeAvAAAAEXVzZXJARWxhZENvbXB1dGVyAQ==
    -----END OPENSSH PRIVATE KEY-----